import { ColDef } from "ag-grid-community";
import { PortfolioOverview } from "../../../../../models/PortfolioOverview";
import { rowIndexValueGetter } from "../../../../../utils/ValueGetters";
import { numberFormatter } from "../../../../../utils/Formaters";

export const portfolioOverviewColDefs: Array<ColDef<PortfolioOverview>> = [
  {
    headerName: "#",
    valueGetter: rowIndexValueGetter,
    pinned: "left",
    enableRowGroup: false,
    suppressMenu: true,
    sortable: false,
    filter: false,
  },
  { field: "portfolioName", headerName: "Portfolio Name", minWidth: 100 },
  { field: "department", headerName: "Department", minWidth: 100 },
  { field: "investmentType", headerName: "Investment Type", minWidth: 100 },
  {
    field: "currentValue",
    headerName: "Current Value",
    minWidth: 100,
    valueFormatter: numberFormatter,
  },
  {
    field: "initialInvestment",
    headerName: "Initial Investment",
    minWidth: 100,
  },
  { field: "roi", headerName: "ROI", minWidth: 100 },
  { field: "riskLevel", headerName: "Risk Level", minWidth: 100 },
  {
    field: "assetAllocation.stocks",
    headerName: "Stocks",
    minWidth: 100,
  },
  {
    field: "assetAllocation.bonds",
    headerName: "Bonds",
    minWidth: 100,
  },
  { field: "benchmark", headerName: "Benchmark", minWidth: 100 },
  { field: "manager", headerName: "Manager", minWidth: 100 },
  // {
  //   field: "maturity",
  //   headerName: "Maturity",
  //   minWidth: 100,
  //   filter: "agDateColumnFilter",
  //   filterParams: filterDateParams,
  // },
  // { field: "traderName", headerName: "Trader Name", minWidth: 130 },
  // {
  //   field: "bidSpreadToBenchmark",
  //   headerName: "Bid Spread To Benchmark",
  //   minWidth: 150,
  //   editable: true,
  //   type: "numericColumn",
  //   filter: "agNumberColumnFilter",
  //   valueFormatter: numberFormatter,
  //   enableRowGroup: false,
  //   cellEditor: selectOnFocusNumberEditor,
  // },
  // {
  //   field: "cibcOfficialBidPrice",
  //   headerName: "Px Bid",
  //   minWidth: 100,
  //   editable: true,
  //   type: "numericColumn",
  //   filter: "agNumberColumnFilter",
  //   valueFormatter: numberFormatter,
  //   enableCellChangeFlash: true,
  //   enableRowGroup: false,
  //   cellEditor: selectOnFocusNumberEditor,
  // },
  // {
  //   field: "cibcOfficialAskPrice",
  //   headerName: "Px Ask",
  //   type: "numericColumn",
  //   minWidth: 80,
  //   maxWidth: 100,
  //   editable: true,
  //   filter: "agNumberColumnFilter",
  //   valueFormatter: numberFormatter,
  //   enableCellChangeFlash: true,
  //   enableRowGroup: false,
  //   cellEditor: selectOnFocusNumberEditor,
  // },
  // {
  //   field: "cibcOfficialBidYield",
  //   headerName: "Yld Cnv Bid",
  //   minWidth: 80,
  //   maxWidth: 100,
  //   editable: true,
  //   type: "numericColumn",
  //   filter: "agNumberColumnFilter",
  //   valueFormatter: numberFormatter,
  //   enableCellChangeFlash: true,
  //   enableRowGroup: false,
  //   cellEditor: selectOnFocusNumberEditor,
  // },
  // {
  //   field: "benchmarkSecurity",
  //   headerName: "Bnchmrk Sec Des",
  //   minWidth: 150,
  //   editable: true,
  //   cellEditor: AutoCompleteEditor,
  //   cellEditorParams: {
  //     options: searchBenchmarks,
  //   },
  // },
];
